####################################################
#          Circuit Simulation Algorithms           #
#################################################### 
# Authors: Georgia-Despoina Tzanetou               #
#          Zisis Balatsos                          #
#                                                  #
#       University of Thessaly Volos, 2023         #
#                                                  #
####################################################

###################################################################################################
#   makefile for compiling all necessary (.c and .h) files of the project and producing the       #
#   corresponding object files along with the default built executable (a.out) generated by gcc.  #
###################################################################################################

CC = gcc
CFLAGS = -Wall -g -I/usr/include/gsl/
#CFLAGS = -O2 -DNDEBUG
OBJ = netlist_parser.o MNA_DC_system_creation.o MNA_DC_system_direct_methods.o MNA_DC_system_iterative_methods.o parser_tool.o SPARSE_DC_system_creation.o csparse.o SPARSE_DC_system_direct_methods.o SPARSE_DC_system_iterative_methods.o TRAN_DC_system_creation.o TRAN_sweep.o AC_TRAN_sweep.o

# top level goal

all: $(OBJ)
	$(CC) $(CFLAGS) $(OBJ) `gsl-config --cflags --libs`

netlist_parser.o: netlist_parser.c netlist_parser.h
	$(CC) $(CFLAGS) -c netlist_parser.c

MNA_DC_system_creation.o: MNA_DC_system_creation.c MNA_DC_system_creation.h
	$(CC) $(CFLAGS) -c MNA_DC_system_creation.c

MNA_DC_system_direct_methods.o: MNA_DC_system_direct_methods.c MNA_DC_system_direct_methods.h
	$(CC) $(CFLAGS) -c MNA_DC_system_direct_methods.c

MNA_DC_system_iterative_methods.o: MNA_DC_system_iterative_methods.c MNA_DC_system_iterative_methods.h
	$(CC) $(CFLAGS) -c MNA_DC_system_iterative_methods.c

SPARSE_DC_system_creation.o: SPARSE_DC_system_creation.c SPARSE_DC_system_creation.h
	$(CC) $(CFLAGS) -c SPARSE_DC_system_creation.c

csparse.o: csparse.c csparse.h
	$(CC) $(CFLAGS) -c csparse.c

SPARSE_DC_system_direct_methods.o: SPARSE_DC_system_direct_methods.c SPARSE_DC_system_direct_methods.h
	$(CC) $(CFLAGS) -c SPARSE_DC_system_direct_methods.c

SPARSE_DC_system_iterative_methods.o: SPARSE_DC_system_iterative_methods.c SPARSE_DC_system_iterative_methods.h
	$(CC) $(CFLAGS) -c SPARSE_DC_system_iterative_methods.c

TRAN_DC_system_creation.o: TRAN_DC_system_creation.c TRAN_DC_system_creation.h
	$(CC) $(CFLAGS) -c TRAN_DC_system_creation.c

TRAN_sweep.o: TRAN_sweep.c TRAN_sweep.h
	$(CC) $(CFLAGS) -c TRAN_sweep.c

AC_TRAN_sweep.o: AC_TRAN_sweep.c AC_TRAN_sweep.h
	$(CC) $(CFLAGS) -c AC_TRAN_sweep.c

parser_tool.o: parser_tool.c netlist_parser.h MNA_DC_system_creation.h MNA_DC_system_direct_methods.h MNA_DC_system_iterative_methods.h SPARSE_DC_system_creation.h csparse.h SPARSE_DC_system_direct_methods.h SPARSE_DC_system_iterative_methods.h TRAN_DC_system_creation.h TRAN_sweep.h AC_TRAN_sweep.h
	$(CC) $(CFLAGS) -c parser_tool.c

clean: 
	rm all $(OBJ)